version: '3.8'

services: 
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=mssqlserver-secret
      - ACCEPT_EULA=Y
    volumes:
      - ./mssql/log:/var/opt/mssql/log
      - ./mssql/data:/var/opt/mssql/data
    ports:
      - "1433:1433"
    deploy:
      resources: 
        limits: 
          cpus: '2'
          memory: '2048m'
