version: '3.8'
services:
  pgsql:
    image: postgres:15-alpine
    command: ["postgres", "-c", "log_statement=all"]
    user: root
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=postgres-secret
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./logs:/logs:rw