version: '3.7'
services:  
  eventstore:
    image: eventstore/eventstore:20.10.2-bionic
    hostname: 'todo-eventstore'
    ports:
      - '2114:2113'
      - '1114:1113'
    environment:
      EVENTSTORE_CLUSTER_SIZE: 1
      EVENTSTORE_RUN_PROJECTIONS: All
      EVENTSTORE_START_STANDARD_PROJECTIONS: 'true'
      EVENTSTORE_EXT_TCP_PORT: 1113
      EVENTSTORE_HTTP_PORT: 2113
      EVENTSTORE_INSECURE: 'true'
      EVENTSTORE_ENABLE_EXTERNAL_TCP: 'true'
      EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: 'true'
    volumes:
      - ./data/eventstore/data:/var/lib/eventstore
  
  rabbitmq:
    image: rabbitmq:3-management
    hostname: 'todo-rabbitmq'
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ./data/rabbitmq/data:/var/lib/rabbitmq
      - ./data/rabbitmq/log:/var/log/rabbitmq