version: '3.7'
services:  
  rabbitmq:
    image: rabbitmq:3-management
    hostname: 'todo-rabbitmq'
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - ./data:/var/lib/rabbitmq
      - ./log:/var/log/rabbitmq